name: Publish to Packagist

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Update Packagist
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=streammachineio&apiToken=${{secrets.PACKAGIST_API_TOKEN}}' -d'{"repository":{"url":"https://packagist.org/packages/streammachineio/php-driver"}}'
